config/routes.rb
Rails.application.routes.draw do
  # comments
  resources :comments
  # topics
  get 'topics/most_view' => 'topics#most_view'
  get 'topics/search_result' => 'topics#search_result'
  resources :topics
  # users
  resources :users
  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'
  get 'admin' => 'users#admin'

  # home
  get '/' => 'home#top'
  get '/about' => 'home#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 140}}

  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  is_impressionable :counter_cache => true

  paginates_per 5

  validates :title, {presence: true, length: {maximum: 40}}
  validates :content, {presence: true, length: {maximum: 180}}

  belongs_to :user
  has_many :comments

  def self.search(title)
    where('title LIKE ?', "%#{title}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX ,message: "形式が間違っています" }

  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy

  def admin?
    admin_status == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to("/topics")
    end
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to(topics_path)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit]}

  def index
    @comments = Comment.all
  end

  def create
    @comment = @current_user.comments.new(
      content: params[:comment][:content],
      topic_id: params[:comment][:topic_id]
    )
    if @comment.save
      flash[:notice] = "コメントを投稿しました"
      redirect_back(fallback_location: topics_path)
    else
      @topic_user = Topic.find_by(id: params[:comment][:topic_id])
      render("topics/show")
    end
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    if @comment.update(content: params[:comment][:content])
      flash[:notice] = "コメントを編集しました"
      redirect_to(topic_path(@comment.topic_id))
    else
      render("comments/edit")
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    flash[:notice] = "コメントを削除しました"
    redirect_back(fallback_location: topics_path)
  end

  private

  def ensure_correct_user
    @comment = Comment.find_by(id: params[:id])
    if @comment.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to(topics_path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user

  def top
  end

  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update]}
  impressionist :actions => [:show, :index]

  def index
    @topics = Topic.all.order(created_at: "desc").page(params[:page]).per(5)
  end

  def most_view
    @most_viewed_topics = Topic.order('impressions_count DESC').take(3)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(
      title: params[:topic][:title],
      content: params[:topic][:content],
      user_id: @current_user.id
    )
    if @topic.save
      flash[:notice] = "トピックを作成しました"
      redirect_to(topics_path)
    else
      render("new")
    end
  end

  def show
    @topic_user = Topic.find_by(id: params[:id])
    @comment = Comment.new
    impressionist(@topic_user, nil, unique: [:session_hash])
  end

  def edit
    @topic = Topic.find_by(id: params[:id])
  end

  def update
    @topic = Topic.find_by(id: params[:id])
    if @topic.update(title: params[:topic][:title], content: params[:topic][:content])
      flash[:notice] = "トピックの情報を編集しました"
      redirect_to(topic_path(@topic.id))
    else
      render("edit")
    end
  end

  def destroy
    @topic = Topic.find_by(id: params[:id])
    @topic.destroy
    flash[:notice] = "トピックを削除しました"
    if @current_user.admin?
      redirect_to(admin_path)
    else
      redirect_to("/")
    end
  end

  def search_result
    @topics = Topic.search(params[:title])
    @title = params[:title]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  before_action :ensure_correct_admin, {only: [:admin]}

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      profile_image: "default_image.jpg",
      password: params[:user][:password],
      profile: "よろしくお願いします。"
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to(user_path(@user.id))
    else
      render("new")
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to(topics_path)
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("login_form")
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to(login_path)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])

    if params[:user][:image]
      @user.profile_image = "#{@user.id}.jpg"
      image = params[:user][:image]
      File.binwrite("public/profile_images/#{@user.profile_image}", image.read)
    end

    if @user.update(name: params[:user][:name], email: params[:user][:email], profile: params[:user][:profile])
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to(user_path(@user.id))
    else
      render("edit")
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    flash[:notice] = "アカウントを削除しました"
    if @current_user.admin?
      redirect_to(admin_path)
    else
      redirect_to("/")
    end
  end

  def admin
    @users = User.page(params[:page])
    @topics = Topic.page(params[:page])
  end

  private

  def ensure_correct_admin
    if @current_user.admin_status != true
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d %H:%M ")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def t_ensure_correct_user
    @topic_user.user_id == @current_user.id
  end

  def comment_user?(comment: comment)
    comment.user_id == @current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def u_ensure_correct_user
    @user.id == @current_user.id
  end
end

app/views/comments/edit.html.erb
<div class="container">
  <h1 class="form-heading">コメント編集</h1>
  <%= form_with(model: @comment, local: true) do |form| %>
  <form>
  <div class="form-group">
    <% @comment.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
    <% end %>
    <%= form.text_area :content, class: "form-control", rows: "3" %>
    <%= form.submit "更新", class: "btn btn-primary my-2" %>
  </div>
  </form>
  <% end %>
</div>

app/views/home/about.html.erb
<div class="container">
  <h4>Boardについて</h4>
  <h6><span class="border-bottom border-danger">Boardってなに？</span></h6>
    <p>どんなジャンルでもカバーする掲示板です。気楽に書き込んで下さい。</p>
  <h6><span class="border-bottom border-danger">最低限のルールは？</span></h6>
    <p>他人に迷惑をかけるのはやめましょう。。。<br><br>必要以上の馴れ合いは慎しむとか、暴言や第三者を不快にする書き込みはしないとか、悪質な削除要請や自己中心的な発言はひかえるとか、どれもむずかしくないことです。<br>また、一般人の誹謗中傷・私生活情報暴露は禁止します。</p>
  <h6><span class="border-bottom border-danger">他に気をつけることは？</span></h6>
    <p>まず、他人が見て面白いことを書きましょう。大勢の読者がいることを意識してください。<br>またトピックを立てる前に、同じような内容のものがないか確認するのも忘れないでください。</p>
</div>

app/views/home/top.html.erb
<div class="jumbotron">
    <h1>今の気持ちをつぶやいてみよう</h1>
    <p>※この掲示板のご利用は利用者各位の判断にお任せしています</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <%= render 'partial/navbar' %>
    </header>
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand mb-0 h1">
    <% if @current_user %>
      <%= link_to("Board", topics_path) %>
    <% else %>
      <%= link_to("Board", "/") %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if @current_user %>
      <li class="nav-item">
        <%= link_to("人気トピック", topics_most_view_path, {class: "nav-link"}) %>
      </li>
      <li class="nav-item">
        <%= link_to("トピック作成", new_topic_path, {class: "nav-link"}) %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown">
          <span class="far fa-user"><%= "ログイン中：#{@current_user.name}" %></span>
        </a>
        <div class="dropdown-menu">
          <%= link_to("マイページ", user_path(@current_user.id), {class: "nav-link fas fa-home"}) %>
          <%= link_to("ログアウト", logout_path, {method: :post, data:
          {confirm: "ログアウトしますか？"}, class: "nav-link fas fa-sign-out-alt"}) %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to("Boardについて", about_path, {class: "nav-link"}) %>
      </li>
      <li class="nav-item">
        <%= link_to("新規登録", new_user_path, {class: "nav-link"}) %>
      </li>
      <li class="nav-item">
        <%= link_to("ログイン", login_path, {class: "nav-link"}) %>
      </li>
    <% end %>
    <% if @current_user.present? && @current_user.admin? %>
      <li>
        <%= link_to("管理者ページ", admin_path, {class: "nav-link"}) %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/topics/edit.html.erb
<div class="container">
  <h1 class="form-heading">トピック編集</h1>
  <%= form_with(model: @topic, local: true) do |form| %>
  <form>
    <div class="form-group">
      <% @topic.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <%= message %>
        </div>
      <% end %>
      <h5><%= form.label :title, "タイトル", class: "m-0" %></h5>
        <%= form.text_field :title, class: "form-control mb-3" %>
      <h5><%= form.label :content, "内容", class: "m-0" %></h5>
        <%= form.text_area :content, class: "form-control" %>
      <%= form.submit "更新", class: "btn btn-primary my-2" %>
    </div>
  </form>
  <% end %>
</div>

app/views/topics/index.html.erb
<div class="container">
  <%= form_with(url: topics_search_result_path, local: true, method: :get) do |form| %>
    <%= form.text_field :title, class: "form-control my-2", placeholder: "全トピックから検索" %>
    <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
  <%= page_entries_info @topics %>
  <% @topics.each do |topic| %>
    <div class="card mx-auto my-1">
      <div class="row">
      <div class="col-md-12">
            <div class="card-body">
              <h5><%= link_to(topic.title, topic_path(topic.id), {class: "card-title"}) %></h5>
              <p class="card-text"><%= topic.content %></p>
              作成者<%= link_to(topic.user.name, user_path(topic.user.id)) %>
              <p class="card-text"><small class="text-muted">トピック作成日<%= simple_time(topic.created_at) %></small></p>
              <small class="text-muted"><%= "#{topic.impressionist_count}view" %></small>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <%= paginate @topics %>
</div>

app/views/topics/most_view.html.erb
<div class="container">
  <%= form_with(url: topics_search_result_path, local: true, method: :get) do |form| %>
    <%= form.text_field :title, class: "form-control my-2", placeholder: "全トピックから検索" %>
    <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
  <% @most_viewed_topics.each do |topic| %>
    <div class="card mx-auto my-1">
      <div class="row">
      <div class="col-md-12">
            <div class="card-body">
              <h5><%= link_to(topic.title, topic_path(topic.id), {class: "card-title"}) %></h5>
              <p class="card-text"><%= topic.content %></p>
              作成者<%= link_to(topic.user.name, user_path(topic.user.id)) %>
              <p class="card-text"><small class="text-muted">トピック作成日<%= simple_time(topic.created_at) %></small></p>
              <small class="text-muted"><%= "#{topic.impressionist_count}view" %></small>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<div class="container">
  <h1 class="form-heading">トピック作成</h1>
  <%= form_with(model: @topic, local: true) do |form| %>
    <form>
      <% @topic.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <%= message %>
        </div>
      <% end %>
      <h5><%= form.label :title, "タイトル", class: "m-0" %></h5>
        <%= form.text_field :title, class: "form-control mb-3" %>
      <h5><%= form.label :content, "内容", class: "m-0" %></h5>
        <%= form.text_area :content, class: "form-control" %>
        <%= form.submit "トピック作成", class: "btn btn-primary my-2" %>
    </form>
  <% end %>
</div>

app/views/topics/search_result.html.erb
<div class="container">
  <%= form_with(url: topics_search_result_path, local: true, method: :get) do |form| %>
    <%= form.text_field :title, class: "form-control my-2", placeholder: "全トピックから検索" %>
    <%= form.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
  <%= "”#{@title}”を検索しました。" %>
  <%= "トピック#{@topics.count}件" %>
  <% if @topics.count == 0 %>
    <h3>懸命に探してみましたが、見つかりませんでした。</h3>
    <p>検索のヒント</p>
    <ul>
      <li>キーワードを短くしてみたり、数を減らしてみてください。</li>
      <li>キーワードの誤字、脱字がないか確認してください。</li>
      <li>別のキーワードを試してみてください。</li>
      <li>もっと一般的なキーワードに変えてみてください。</li>
    </ul>
  <% else %>
  <h3>検索結果</h3>
    <% @topics.each do |topic| %>
    <div class="row">
      <div class="col-sm-6">
        <div class="card-group">
          <div class="card">
            <div class="card-body">
              <%= link_to(topic.title, topic_path(topic.id), {class: "card-title"}) %>
              <p class="card-text"><%= topic.content %></p>
              <%= link_to("作成者#{topic.user.name}", user_path(topic.user.id)) %>
            </div>
            <div class="card-footer text-muted">
              トピック作成日<%= simple_time(topic.created_at) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="card mx-auto my-2">
    <div class="col-md-8">
      <div class="card-body">
      <h2 class="card-title"><%= @topic_user.title %></h2>
      <p class="card-text"><%= @topic_user.content %></p>
      <% if t_ensure_correct_user %>
        <%= link_to("編集", edit_topic_path(@topic_user.id)) %>
        <%= link_to("削除", topic_path(@topic_user.id), method: :delete, data:
        { confirm: "本当に#{@topic_user.title}を削除してよろしいですか？"}) %>
      <% end %>
      </div>
    </div>
  </div>
  <% @topic_user.comments.each do |comment| %>
  <div class="media">
    <img src="<%= "/profile_images/#{comment.user.profile_image}" %>" class="bd-placeholder-img" width="64" height="64">
    <div class="media-body">
      <h5 class="mt-0"><%= link_to(comment.user.name, user_path(comment.user_id)) %></h5>
      <%= comment.content %>
      <% if comment_user?(comment: comment) %>
        <%= link_to("編集", edit_comment_path(comment.id)) %>
        <%= link_to("削除", comment_path(comment.id), method: :delete, data:
        { confirm: "本当に#{comment.content}を削除してよろしいですか？"}) %>
      <% end %>
      <p class="card-text"><small class="text-muted"><%= simple_time(comment.created_at) %></small></p>
    </div>
  </div>
  <% end %>
  <div class="form_group my-2">
  <%= form_with(model: @comment, url: comments_path, local: true) do |form| %>
    <% @comment.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
    <%= form.hidden_field :topic_id, value: @topic_user.id %>
    <%= form.text_area :content, class: "form-control", rows: "2", placeholder: "コメントを書く" %>
    <%= form.submit "投稿", class: "btn btn-primary my-2" %>
    <% end %>
  </div>
</div>

app/views/users/admin.html.erb
<h1>管理者ページ</h1>
<h2>トピック一覧</h2>
<div class="container">
<%= page_entries_info @topics %>
  <% @topics.each do |topic| %>
    <div class="row">
      <div class="media">
        <img src="<%= "/profile_images/#{topic.user.profile_image}" %>" class="bd-placeholder-img" width="64" height="64">
        <div class="media-body">
          <h5 class="mt-0"><%= link_to(topic.title, topic_path(topic.id)) %></h5>
          <%= topic.content %>
          作成者<%= link_to(topic.user.name, user_path(topic.user_id)) %>
          <p class="card-text"><small class="text-muted">
            トピック作成日<%= simple_time(topic.created_at) %><br>
            <%= link_to("トピック削除", topic_path(topic.id), method: :delete, data:
            { confirm: "本当にこのトピックを削除してよろしいですか？"}) %>
          </small></p>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
<%= paginate @topics %>
</div>
<h2>ユーザー一覧</h2>
<div class="container">
<%= page_entries_info @users %>
  <% @users.each do |user| %>
  <div class="row">
    <div class="media">
      <img src="<%= "/profile_images/#{user.profile_image}" %>" class="bd-placeholder-img" width="64" height="64">
      <div class="media-body">
        <h5 class="mt-0"><%= link_to(user.name, user_path(user.id)) %></h5>
        <p class="card-text"><small class="text-muted">
          ユーザー登録日<%= simple_time(user.created_at) %><br>
          <%= link_to("アカウント削除", user_path(user.id), method: :delete, data:
          { confirm: "本当にこのアカウントを削除してよろしいですか？"}) %>
        </small></p>
      </div>
    </div>
  </div>
  <hr>
  <% end %>
<%= paginate @users %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1 class="form-heading">アカウント編集</h1>
  <%= form_with(model: @user, local: true) do |form| %>
  <form>
  <div class="form-group">
    <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
    <% end %>
    <h5><%= form.label :name, "ユーザー名", class: "m-0" %></h5>
    <%= form.text_field :name, class: "form-control mb-3" %>
    <h5><%= form.label :image, "画像" %></h5>
    <%= form.file_field :image, class: "mb-3" %>
    <h5><%= form.label :email, "メールアドレス", class: "m-0" %></h5>
    <%= form.text_field :email, class: "form-control mb-3" %>
    <h5><%= form.label :profile, "プロフィール", class: "m-0" %></h5>
    <%= form.text_area :profile, class: "form-control mb-3", rows: "3" %>
    <%= form.submit "更新", class: "btn btn-primary my-2" %>
  </div>
  </form>
  <% end %>
</div>

app/views/users/login_form.html.erb
<div class="container">
  <h2 class="form-heading">ログイン</h2>
  <%= form_with(model: @user, local: true) do |form| %>
    <form>
      <% if @error_message %>
        <div class="alert alert-danger" role="alert">
          <%= @error_message %>
        </div>
      <% end %>
      <h5><%= form.label :email, "メールアドレス", class: "m-0" %></h5>
        <%= form.text_field :email, class: "form-control mb-3" %>
      <h5><%= form.label :password, "パスワード", class: "m-0" %></h5>
        <%= form.text_field :password, class: "form-control" %>
        <%= form.submit "ログイン", class: "btn btn-primary my-2" %>
    </form>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="form-heading">新規ユーザー登録</h2>
  <%= form_with(model: @user, local: true) do |form| %>
    <form>
      <% @user.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <%= message %>
        </div>
      <% end %>
      <h5><%= form.label :name, "ユーザー名", class: "m-0" %></h5>
        <%= form.text_field :name, class: "form-control mb-3" %>
      <h5><%= form.label :email, "メールアドレス", class: "m-0" %></h5>
        <%= form.text_field :email, class: "form-control mb-3" %>
      <h5><%= form.label :password, "パスワード", class: "m-0" %></h5>
        <%= form.text_field :password, class: "form-control" %>
        <%= form.submit "新規登録", class: "btn btn-primary my-2" %>
    </form>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>マイページ</h1>
  <div class="card mx-auto" style="width: 25%">
    <img src="<%= "/profile_images/#{@user.profile_image}" %>" class="bd-placeholder-img card-img-top">
    <div class="card-body">
      <h2 class="card-title"><%= @user.name %></h2>
      <h5 class="card-title">プロフィール</h5>
      <p class="card-text"><%= @user.profile %></p>
      <% if u_ensure_correct_user %>
        <%= link_to("プロフィール編集", edit_user_path, class: "btn btn-primary") %>
      <% end %>
    </div>
  </div>
  <h2>投稿一覧</h2>
  <% @user.comments.each do |comment| %>
  <div class="card mx-auto my-1">
    <div class="row">
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to(comment.topic.title, topic_path(comment.topic_id)) %>
          </h5>
          <p class="card-text"><%= comment.content %>
            <% if comment_user?(comment: comment) %>
            <%= link_to("編集", edit_comment_path(comment.id)) %>
            <%= link_to("削除", comment_path(comment.id), method: :delete, data:
            { confirm: "本当に#{comment.content}を削除してよろしいですか？"}) %>
            <% end %>
          </p>
          <p class="card-text"><small class="text-muted"><%= simple_time(comment.created_at) %></small></p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>